### ISSUE TITLE
Mehr Sourcen übergeben

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/plyr#27]
z.B. zusätzlich webm , ogg etc.

**Comment by dpf-dd** [comment]
Ich bin ja der Meinung, dass man das hier einfach dicht machen kann. MP4 hat sich durchgesetzt und webm/ogg und Konsorten sind imho obsolet geworden...
Nur Opera Mini kann es nicht, aber der kann auch kein webm/ogg. Von daher...

https://caniuse.com/#search=mp4
