### ISSUE TITLE
controls werden nicht angezeigt

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/plyr#28]
wenn ich 'controls' definiere werden diese im frontend (ff + chrome / windows) nicht erwartungsgemäß angezeigt. es wird folgendes html ausgegeben:

`<video class="rex-plyr" data-plyr-config='{"controls":["play-large","play","progress","airplay","pip"]}'playsinline volume=1 poster="/images/poster.jpg">`

wenn ich die anführungszeichen in 'data-plyr-config' anpasse und eine leerstelle zu 'playsinline' anpasse, werden die controls angezeigt:

`<video class="rex-plyr" data-plyr-config="{ 'controls': ['play-large','play','progress','airplay','pip'] }" playsinline  volume=1 poster="/images/poster.jpg">`

**Comment by skerbis** [comment]
Danke: https://github.com/FriendsOfREDAXO/plyr/commit/fdea9125a32c65db660c97e33991d6ff3fdd151f
