### ISSUE TITLE
Links können nicht gespeichert werden

### ISSUE THREAD

**Issue by Himra** [FriendsOfREDAXO/plyr#29]
Hallo Zusammen,
ich hab soeben das Addon PLYR installiert und ein Modul wie in der Hilfe beschrieben angelegt.
Lokale Videos laufen, sobald ich aber ein Youtube oder Vimeo Link einfüge, lässt sich dies im Backend nicht speichern. Das Modul reagiert einfach nicht. 

getestet unter:
WIN7 -> Firefox 70.0.1 (64-Bit) und IE11

Systemdaten:
REDAXO 5.8.1
PHP 7.2.18
DB 5.7.23

Danke für eure Hilfe

**Comment by skerbis** [comment]
Gibt es irgendwelche Informationen im Systemlog?

**Comment by Himra** [comment]
hab´s grad nochmals getestet im Systemlog kommt leider nichts.
auch sonst wird keine Fehlermeldung angezeigt

**Comment by Himra** [comment]
hab soeben noch den Cache gelöscht und den Debug-Modus aktiviert. Funktioniert leider auch nicht und Fehlermeldung kommt auch keine.

**Comment by skerbis** [comment]
Die genannte Fehlerbeschreibung tritt auch bei anderen Modulen/Addons auf. (geklärt in SLACK).
