### ISSUE TITLE
allow Fullscreen iframe an orientation change event

### ISSUE THREAD

**Issue by danielellm** [FriendsOfREDAXO/plyr#30]
where can i ad allow fullscreen for all browsers in iframe (vimeo)
allowfullscreen="allowfullscreen"
mozallowfullscreen="mozallowfullscreen" 
msallowfullscreen="msallowfullscreen" 
oallowfullscreen="oallowfullscreen" 
webkitallowfullscreen="webkitallowfullscreen"

ich hätte gerne fullscreen video aufn mobile device  im landscape mode, also beim drehen des phones..

**Comment by skerbis** [comment]
Bitte in der Anletung des Vendors nachschauen

**Comment by danielellm** [comment]
Was meinst du?
Wo finde ich die?

Thomas Skerbis <notifications@github.com> schrieb am Mo., 9. Dez. 2019,
23:46:

**Comment by skerbis** [comment]
Hier https://github.com/sampotts/plyr

**Comment by danielellm** [comment]
vielen dank

ich habe die playr_init.js in /assets/addons/plyr
wie folgt ergänzt

`document.addEventListener("DOMContentLoaded", function(){

 const players = Plyr.setup('.rex-plyr',{
	 youtube: { 
		 noCookie: true
	 },
  
   fullscreen: { 
   enabled: true, 
   fallback: true, 
   iosNative: false }
 }); 
 




});

const players = new Plyr('.rex-plyr');
players.on('play', event => {
    const instance = event.detail.plyr; 
    
screen.orientation.addEventListener("change", function() {
   
   if(screen.orientation.type = 'landscape-primary') {
  players.fullscreen.enter();
  } 
  if(screen.orientation.type = 'portrait-primary') {
  players.fullscreen.exit();
  }
	
	
}, false);

  window.addEventListener('orientationchange', function() {
 
            if (window.orientation & 2) {
                players.fullscreen.enter();
            } else {
                players.fullscreen.exit();
            }

});

});`

**Comment by skerbis** [comment]
Magst es in die Readme schreiben und erklären?

**Comment by skerbis** [comment]
Ist jetzt in der Readme 👍
