### ISSUE TITLE
Bitte konkrete Beispiele mit Ausgabecode ergänzen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/plyr#33]
Schaue mir gerade das Addon zum ersten Mal an und kapiere es nicht. Einbindung ist klar.

* Wie komme ich an das Custom Link Feld?
* Wie gebe ich ein Youtube-iframe aus?
* Wie ich kann ich den Ausgabecode des Youtube-iframes anpassen?

Außerdem war ich irritiert, keinen Backend-Menüpunkt zu finden.

**Comment by skerbis** [comment]
- Das AddOn brauch keinen Menüpunkt. 
- Die Eingabe des CustomLinkfields wird erklärt in der Readme

> Wie gebe ich ein Youtube-iframe aus?
URL zu einer YouTube-Adresse eingeben

**Comment by alexplusde** [comment]
> Die Eingabe des CustomLinkfields wird erklärt in der Readme

Mir war nicht klar, dass dieses bei MForm immer mit dabei ist.

**Comment by skerbis** [comment]
ich close dann mal
