### ISSUE TITLE
Vimeo:  DoNotTrack Parameter ermöglichen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/plyr#37]
?dnt=1
https://vimeo.zendesk.com/hc/de/articles/360001494447-Verwendung-von-Player-Parametern

**Comment by skerbis** [comment]
Bitte altuelle Github-Version testen. Rückmeldung erwünscht.

**Comment by isospin** [comment]
funktioniert!

**Comment by skerbis** [comment]
Danke
