### ISSUE TITLE
Icons lokal nachladen

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/plyr#38]
Icons sollten nicht von einem CDN nachgeladen werden.
https://github.com/sampotts/plyr/blob/b444aa3a98079cc5b4af16dc3dc5d808aec24342/src/js/config/defaults.js#L64

**Comment by skerbis** [comment]
Bitte aktuelle Github Version testen, Danke für den Hinweis

**Comment by TobiasKrais** [comment]
Man bist du schnell! Meine Netzwerkanalyse im Firefox sagt, dass das Play Icon immer noch vom CDN nachgeladen wird.

**Comment by skerbis** [comment]
??? ... hmm

**Comment by TobiasKrais** [comment]
Klappt es bei dir?

**Comment by skerbis** [comment]
Addon neu installiert? Cache gelöscht?

**Comment by skerbis** [comment]
Bei mir kommt's von /assets/addons/plyr/vendor/plyr/dist/plyr.svg

**Comment by skerbis** [comment]
<img width="469" alt="Bildschirmfoto 2020-11-16 um 16 33 47" src="https://user-images.githubusercontent.com/791247/99273632-93994e00-2829-11eb-98bc-2362db6ee985.png">

**Comment by TobiasKrais** [comment]
Passt. ich mach den Issue zu. Vielen Dank für die Mega schnelle Lösung!
