### ISSUE TITLE
Icons werden auf Unterseiten nicht geladen da ein Slash am Anfang fehlt

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/plyr#40]
https://github.com/FriendsOfREDAXO/plyr/blob/3a83d8e7e638f8d753305c383b8fb88cb3e7fa2f/assets/plyr_init.js#L9

und

https://github.com/FriendsOfREDAXO/plyr/blob/3a83d8e7e638f8d753305c383b8fb88cb3e7fa2f/assets/plyr_init.js#L10

**Comment by skerbis** [comment]
ist bereits so, danke
