### ISSUE TITLE
Loop und autostart als Option in die Controls geht nicht

### ISSUE THREAD

**Issue by ritzfritz** [FriendsOfREDAXO/plyr#43]

**Comment by skerbis** [comment]
@ritzfritz  PR welcome

**Comment by dpf-dd** [comment]
https://github.com/dpf-dd/plyr/pull/1

**Comment by dpf-dd** [comment]
https://github.com/dpf-dd/plyr/pull/1/

Hier der PR. Aber GitHub nervt mich. Ich kann das iwie nur als PR für meinen Fork committen. Keine Ahnung wie ich das hier rein kriege...

**Comment by skerbis** [comment]
jetzt vom Master den PR starten @dpf-dd ?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/plyr/pull/45
