### ISSUE TITLE
Play Icon wird in Unterordner Installation nicht angezeigt

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/plyr#46]
In der `/assets/addons/plyr/plyr_init.js` wird der Pfad so definiert:
`iconUrl: '/assets/addons/plyr/vendor/plyr/dist/plyr.svg'`.

Das Init Script müsste via PHP im Modul generiert werden oder die `plyr_init.js` dynamisch generiert.

**Comment by skerbis** [comment]
Ich verstehe die plyr_init.js für das Frontend nur als Angebot und werde es entsprechend in der Readme klar machen. 
Sie ist auch bewusst nur kurz gehalten.
