### ISSUE TITLE
bei PIP-Modus sollte das Originalvideo weiterhin sichtbar bleiben

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/plyr#50]
Ich teste gerade das PLYR-Addon.
Dabei ist mir die PIP-Funktion ins Auge gefallen.

Eine feine Sache, aber ...
...dabei wird das Originalvideo schwarz geschalten, was doof ist.
Dies sollte weiterhin (pausiert) zu sehen sein.

**Comment by skerbis** [comment]
PIP ist eine Funktion von macOS darauf dürfte der Player keinen Einfluss haben.

**Comment by iceman-fx** [comment]
Verstehe ich nicht.
Aktiviere ich pip. Dann wird mir im Chrome (Windows) das Video in einem kleinen Fenster unten rechts angezeigt.
Soweit so gut.
Aber das Originalvideo ist dann einfach schwarz.

**Comment by skerbis** [comment]
weil es da rausgezogen wird. Das Verhalten ist normal.
Siehe auch hier, das Video wird auch aus dem Youtube widget entfernt: 
<img width="1258" alt="Bildschirmfoto 2021-09-29 um 22 12 46" src="https://user-images.githubusercontent.com/791247/135341571-a0e43cc9-e4bd-4883-a74b-0cffb4d1ef40.png">

**Comment by iceman-fx** [comment]
Bei YouTube wird es bei mir komplett aus dem Seiteninhalt gezogen, so dass kein schwarzer Fleck bleibt.
Bei anderen Seiten bleibt sogar das Video an der Stelle stehen und pausiert oder zeigt das Vorschaubild an.

Der schwarze Fleck im Contest stört.
Kann man in diesem Modus dann nicht das Vorschaubild einfach anzeigen, sofern eines angegeben wurde?

**Comment by skerbis** [comment]
der PIP ist ja dafür da, das Video zur Seite zu legen und wo anders weiter zu surfen.Aber gerne probier mal was passiert wenn du ein poster angibst.
