### ISSUE TITLE
Doku verbessern ...

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/plyr#51]
Leider findet man im Addon (oder hier) keine ausreichende Hilfe zu den möglichen Optionen (und deren Funktion) des Players sowie der korrekten Einbindung mittels REX_PLYR[1].

Einige der Optionen (play-large,airplay) erschließen sich mir nicht.
Und wie man an REX_PLYR[1] korrekt die das ausgewählten Medium (oder URL) übergibt fehlt leider auch.

**Comment by skerbis** [comment]
REX_PLYR nimmt eine einfache REX_VAR an. 
z.B.  REX_VALUE[1] wäre in der Ausgabe REX_PLYR[1]
Es nimmt keine Medialinks an. Daher meine Empfehlung das Custom URL Widget aus mform zu benutzen, so kann man Medien und Urls einfach übergeben. 

Es ist nur eine zusätzliche Hilfe. 
Ich selbst verwende die PHP Methoden.
