### ISSUE TITLE
Starttime: Video ab Sekunde x laufen lassen

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/plyr#53]
Ich würde gerne Videos einbinden, die mitten im Video anfangen, so wie das bei Youtube mit dem Parameter "t" möglich ist.

Also zB: https://youtu.be/Lo3AyaleljA?t=25

Ich habe es selbst versucht, bin aber leider nicht zum Ziel gekommen.

**Comment by skerbis** [comment]
Versuch es mal mit: #t=25,50 oder so ... an der URL

**Comment by omphteliba** [comment]
Funktioniert leider auch nicht.

**Comment by skerbis** [comment]
geht nicht in jedem browser

**Comment by skerbis** [comment]
Aber es scheint auch im Vendor nicht vorgesehen zu sein. 
Habe hier leider keinen Einfluss.

**Comment by omphteliba** [comment]
Ja, das der Vendor das auch nicht drin hat habe ich gesehen. Aber das muss uns ja nicht davon abhalten das trotzdem umzusetzten.

**Comment by skerbis** [comment]
Gerne versuchen.

**Comment by Sysix** [comment]
Laut Dokumentation sollte es gehen.
Sollte ungefähr wie folgt aussehen:

```
const player = new Plyr('#player', {
  /* options */
});

element.addEventListener('ready', (event) => {
  const player = event.detail.plyr;
  player.currentTime = 15
});
```

Vielleicht danach noch `player.play()` wenn nötig :)

**Comment by skerbis** [comment]
Wenn es dafür kein data field gibt, kannst es nur manuell selbst machen je video

**Comment by eaCe** [comment]
https://github.com/sampotts/plyr/issues/623
