### ISSUE TITLE
Video preload verhindern

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/plyr#57]
Eine Option zum verhindern des Video preloads wäre nützlich, besonders wenn viele Videos auf einer Seite vorhanden sind. Bis jetzt löse ich das manuell:
`str_replace('<video', '<video preload="none"', rex_plyr::outputMedia($video_filename,'play-large,play,mute,volume,progress,airplay,pip,loop', rex_url::media($picture)));`

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/plyr/releases/tag/3.13.0

Einfach nopreload im setup parameter mitgeben 😄
