### ISSUE TITLE
plyr 3.13.2: youtube videos funktionieren nicht

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/plyr#61]
nach update auf 3.13.2 werden youtube videos nicht mehr geladen. 
lokale videos & vimeo funktioniert weiterhin. 
im quelltext ist die youtube id nicht zu finden:

`<div class="rex-plyr" data-plyr-provider="vimeo" data-plyr-embed-id="" data-plyr-config='{"controls":["play-large","play","progress","current-time","mute","volume","settings","pip","airplay","fullscreen","nopreload"]}'></div>`

**Comment by skerbis** [comment]
korrigiert

**Comment by isospin** [comment]
der provider wird jetzt richtig gesetzt, aber die embed id fehlt noch

**Comment by isospin** [comment]
https://github.com/FriendsOfREDAXO/plyr/pull/62 sollte das problem beheben
