### ISSUE TITLE
Fehler in der Html-Ausgabe bei der Methode rex_plyr::outputMedia

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/plyr#65]
rex_plyr::outputMedia($fileOrUrl,$config,$poster)
liefert
`<div class="rex-plyrvimeo" data-plyr-provider="vimeo" ...`
anstatt
`<div class="rex-plyr vimeo" data-plyr-provider="vimeo" ...`

plyr 3.20.1

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/plyr/commit/f13958e51917182c8d0e2e5700b2e14962f87599
