### ISSUE TITLE
Poster Darstellung Größe

### ISSUE THREAD

**Issue by novinet-dsteffen** [FriendsOfREDAXO/plyr#69]
Wenn "nopreload" aktiviert ist, wird das Video-Fenster im falschen Format angezeigt. Das sieht man insbesondere, wenn man ein Poster anlegt. In meinem Fall waren Video und Poster Full-HD, das Poster hatte aber schwarze Ränder. Sobald ich auf Play drücke, wird das Video in der richtigen Größe geladen

**Comment by skerbis** [comment]
ist das in der aktuellen Version noch so?
