### ISSUE TITLE
Poster Darstellung Safari

### ISSUE THREAD

**Issue by novinet-dsteffen** [FriendsOfREDAXO/plyr#70]
Sobald ich ein Poster einblende und "nopreload" nicht(!) ausgewählt ist, wird in Safari kein Poster angezeigt.
Lässt sich mit dem folgenden Fix beheben: <style>.plyr__video-wrapper{z-index: 0;}</style>

**Comment by skerbis** [comment]
ist das in der aktuellen Version noch so?
