### ISSUE TITLE
Andere Audioformate unterstützen

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/plyr#71]
Im Prinzip müssten ja auch andere Audioformate funktionieren, z.B. m4a. Plyr selbst unterstützt auch ogg. 
Ich habe dazu auch schon mal folgenden Code ausprobiert, aber anscheinend funktioniert bei meinem Ansatz mp4 nicht immer, darum nicht als Pull Request.

**lib/rex_plyr.php**

Zeile 100:
```
public static function checkAudio($url)
{
    $audio = rex_media::get($url);
    $checkPath = pathinfo($url);
    if ($audio) {
        $extension = strtolower($checkPath['extension']);
        if ('mp3' == $extension || 'm4a' == $extension) {
            return true;
        }
    }
    return false;
}

```

Zeile 229:
```
if (false !== $player->checkAudio($url)) {
    $extension = strtolower(pathinfo($url, PATHINFO_EXTENSION));
    $out = '
        <audio controls class="rex-plyr"' . $setup . $autoplay . $loop . $control_nojs . '>
            <source src="' . $link . '" type="audio/' . $extension . '">
        </audio>
    ';
}
```

**Comment by skerbis** [comment]
ich denke dass mp4 als video interpretiert werden sollte. m4a und mp3 sollten aber funktionieren

**Comment by skerbis** [comment]
fixed https://github.com/FriendsOfREDAXO/plyr/commit/31837d3d7e4e24d48456285c091c1d820cda5005
