### ISSUE TITLE
Audios werden nicht geladen; falscher media-type

### ISSUE THREAD

**Issue by thielpeter** [FriendsOfREDAXO/plyr#74]
In https://github.com/FriendsOfREDAXO/plyr/blob/master/lib/rex_plyr.php#L103 wird bool zurückgegeben. Dadurch wird in https://github.com/FriendsOfREDAXO/plyr/blob/master/lib/rex_plyr.php#L242 `type="audio/1"` gesetzt was wiederum bewirkt dass die Quelle nicht geladen werden kann. Vorschlag: `public static function checkAudio($url): string|bool`

**Comment by skerbis** [comment]
Danke @thielpeter bitte mal den aktuellen Github-Stand testen

**Comment by thielpeter** [comment]
@skerbis Danke für die Anpassung, funktioniert soweit 👍
