### ISSUE TITLE
PLYR verursacht fehlerhaften Aufruf im Consent-Manager Detailbutton

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/plyr#75]
Wenn PLYR installiert ist und man sich auf einer Unterseite der Webseite befindet, dann kann man den Button "Details anzeigen/ausblenden" im Consent-Manager nicht mehr nutzen.

Grund: PLYR stört das Abfangen (Javascript) des Link-"clicks".

https://github.com/FriendsOfREDAXO/consent_manager/issues/312

**Comment by skerbis** [comment]
ok und was kann ich ändern. Das kommt ja vom Verdorr und nicht von meinem JS

**Comment by iceman-fx** [comment]
Entweder müsste der href-Klick per JS abgefangen werden, oder aber es dürfte kein href-Link (href="#") angegeben werden.

**Comment by skerbis** [comment]
und wo findet das statt?

**Comment by iceman-fx** [comment]
Wo das im Code ist kann ich dir jetzt nicht sagen. Aber es ist der Button im cm.

**Comment by skerbis** [comment]
Da ich den Verdorr von Plyr nicht ändern kann. Kann ich hier nichts machen
