### ISSUE TITLE
Callback-Funktionen als Objekte erster Klasse

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/plyr#78]
Wenn man in der Boot.php die Zeile

```php
rex_extension::register('MEDIA_DETAIL_SIDEBAR', 'plyr_mediapool::show_sidebar');
```

ändert in
 ```php
rex_extension::register('MEDIA_DETAIL_SIDEBAR', plyr_mediapool::show_sidebar(...));
```

hätte man eine Schreibweise, die auch von der statischen Code-Analyse der IDE bzw. RexStan sauber erkannt wird. Wurde mit PHP 8.1 eingeführt. Das Addon setzt momentan nur PHP 7.4 voraus.

**Comment by skerbis** [comment]
@christophboecker danke für den Tipp. Da der Vendor nicht mehr weiterentwickelt wird, wird dieses AddOn auch nicht mehr weiterentwickelt. Ich werde was neues bauen.
