### ISSUE TITLE
Projekt umbenennen? Plyr kann auch Audio

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/plyr#9]

**Comment by skerbis** [comment]
Hast Du einen Vorschlag? Media?

**Comment by tbaddade** [comment]
Irgendwas mit **Player** vielleicht ?

**Comment by skerbis** [comment]
Die Audio-Funktion ist allerdings davon abhängig für welchen Player ich mich entscheide. Der Schwerpunkt liegt hier klar bei Video. Wir wollen auch noch API - Funktionen von Vimeo und YouTube einfügen.

**Comment by tbaddade** [comment]
> Die Audio-Funktion ist allerdings davon abhängig für welchen Player ich mich entscheide.

Zumeist bringen diese Player ja Video und Audio Support mit. Mediaelement wäre da noch ein Kandidat.

> Wir wollen auch noch API - Funktionen von Vimeo und YouTube einfügen.

Siehe hier https://github.com/sampotts/plyr#planned-features

**Comment by skerbis** [comment]
@tbaddade Die API-Funktionen möchten wir für PHP bereitstellen unabhängig vom Player. Es ist ja auch möglich das AddOn zu verwenden ohne die mitgelieferten Player zu verwenden.

**Comment by skerbis** [comment]
Ich stelle das jetzt dennoch in den Raum. 
Umbenennen?

**Comment by schuer** [comment]
Wenn der Schwerpunkt bei Video liegt und das auch so bleiben soll, würde ich das AddOn nicht umbenennen, auch wenn es technisch gesehen auch Audio kann.
Sollte es demnächst aber gezielt beides können sollen, dann wäre es sicherlich sinnvoll, es umzubenennen.

**Comment by skerbis** [comment]
Sollte noch mal geprüft werden.

**Comment by skerbis** [comment]
Das AddOn heißt jetzt plyr
